-- TODO: Is any index required?

create table if not exists users
(
    username varchar(20) not null,
    password varchar(20) not null,
    enabled  boolean     not null default true,
    constraint pk_users primary key (username)
);

create table if not exists roles
(
    id       int generated by default as identity primary key,
    username varchar(20) not null,
    role     varchar(20) not null,
    foreign key (username) references users (username),
    constraint uni_username_role unique (role, username)
);

create table if not exists customers
(
    id                int generated by default as identity primary key,
    name              text           not null,
    surname           text           not null,
    credit_limit      numeric(15, 2) not null,
    used_credit_limit numeric(15, 2) not null,
    username          text unique    not null,
    constraint fk_customers_users foreign key (username)
        references users (username) on delete cascade
);

create table if not exists loans
(
    id                    int generated by default as identity primary key,
    customer_id           int            not null,
    loan_amount           numeric(15, 2) not null,
    number_of_installment int            not null,
    create_date           date           not null,
    is_paid               boolean        not null,
    constraint fk_loans_customers foreign key (customer_id)
        references customers (id) on delete cascade
);

create table if not exists loan_installments
(
    id           int generated by default as identity primary key,
    loan_id      int            not null,
    amount       numeric(15, 2) not null,
    paid_amount  numeric(15, 2) not null,
    due_date     date           not null,
    payment_date date,
    is_paid      boolean        not null,
    constraint fk_installments_loans foreign key (loan_id)
        references loans (id) on delete cascade
);
